"""
Environment Variables Configuration
Load API credentials from environment variables or .env file
"""
import os

try:
    from dotenv import load_dotenv
    # Load environment variables from .env file if it exists
    load_dotenv()
except ImportError:
    # python-dotenv not installed, will use environment variables only
    pass

# Groww API Credentials
API_KEY = os.getenv("GROWW_API_KEY", "eyJraWQiOiJaTUtjVXciLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjI1NTc1MTQ3OTMsImlhdCI6MTc2OTExNDc5MywibmJmIjoxNzY5MTE0NzkzLCJzdWIiOiJ7XCJ0b2tlblJlZklkXCI6XCIzOTM4OWJmNS1iODQ2LTRlNWYtOWQxYi1jMzUzMTViMmI4MTVcIixcInZlbmRvckludGVncmF0aW9uS2V5XCI6XCJlMzFmZjIzYjA4NmI0MDZjODg3NGIyZjZkODQ5NTMxM1wiLFwidXNlckFjY291bnRJZFwiOlwiNzcyZTFjODctMGI0ZC00OTMxLTk2MDktZjRmZTA5YjA1MGY3XCIsXCJkZXZpY2VJZFwiOlwiZDU3ZTBjNGQtOTVmOS01ZjllLWI2ZjgtMDMyMmM4ZjViMGUyXCIsXCJzZXNzaW9uSWRcIjpcImE1YWVkMGI4LTU4YTItNDEwMi04N2FhLTJmZjFiZTczYTk4NlwiLFwiYWRkaXRpb25hbERhdGFcIjpcIno1NC9NZzltdjE2WXdmb0gvS0EwYktXeFVXSDNEQTBFbDBoYjBETFBtUk5STkczdTlLa2pWZDNoWjU1ZStNZERhWXBOVi9UOUxIRmtQejFFQisybTdRPT1cIixcInJvbGVcIjpcImF1dGgtdG90cFwiLFwic291cmNlSXBBZGRyZXNzXCI6XCIyNDA1OjIwMTo2ODBjOjgxN2Y6NTk2NzplMWI2OjY5OTE6OGIyZCwxNzIuNjkuMTE5LjEwMywzNS4yNDEuMjMuMTIzXCIsXCJ0d29GYUV4cGlyeVRzXCI6MjU1NzUxNDc5MzI1NX0iLCJpc3MiOiJhcGV4LWF1dGgtcHJvZC1hcHAifQ.dDH4c4phl43LTS2sYg2YvjHe2tozTN03_RVTaH3OcWN_m6_wCvkClwsZu3RZzT1xMzpV88lJK3Imvh3r7TTtkQ")
API_SECRET = os.getenv("GROWW_API_SECRET", "oFk@8qiN)oC6rDDo#CXB$(TB_DBf^LJt")

